"""
Django settings for dacd project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
from dotenv import load_dotenv

dotenv_path = os.path.join(os.path.dirname(__file__), ".env")
load_dotenv(dotenv_path)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.makedirs(os.path.join(BASE_DIR, "media", "imagenes"), exist_ok=True)
os.makedirs(os.path.join(BASE_DIR, "media", "documentos"), exist_ok=True)

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "ve0+qp4lr-_4ke-3&+5m7!$)b0=qxulfl)9r2bd&9^yu79(fkv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ["*"]

# APP DEFINITION
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.humanize",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "logistica",
    "ventas",
    "corsheaders",
    "myapp",
    "seguridad",
    "DAC",
    "TICKETIT",
    "CWS",
    "API",
    "TALENTO",
    "REPORTERIA",
    "CONTABLE",
    "ACTIVO",
    "BANCARIO",
    "GLOBAL",
]
CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "CWS.middleware.CustomErrorMiddleware",
]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


ROOT_URLCONF = "dacd.urls"
FILE_CHARSET = "utf-8"

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "API-Token",
]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "myapp", "templates"),
            os.path.join(BASE_DIR, "logistica", "templates"),
            os.path.join(BASE_DIR, "ventas", "templates"),
            os.path.join(BASE_DIR, "DAC", "templates"),
            os.path.join(BASE_DIR, "TICKETIT", "templates"),
            os.path.join(BASE_DIR, "API", "templates"),
            os.path.join(BASE_DIR, "CWS", "templates"),
            os.path.join(BASE_DIR, "TALENTO", "templates"),
            os.path.join(BASE_DIR, "REPORTERIA", "templates"),
            os.path.join(BASE_DIR, "CONTABLE", "templates"),
            os.path.join(BASE_DIR, "ACTIVO", "templates"),
            os.path.join(BASE_DIR, "BANCARIO", "templates"),
            os.path.join(BASE_DIR, "GLOBAL", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "CWS.context_processors.add_session_variables",
            ],
        },
    },
]

WSGI_APPLICATION = "dacd.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DATABASE_NAME"),
        "USER": os.getenv("DATABASE_USER"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD"),
        "HOST": os.getenv("DATABASE_HOST"),
        "PORT": os.getenv("DATABASE_PORT"),
    },
    "global_nube": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DATABASE_GLOBAL"),
        "USER": os.getenv("DATABASE_GLOBAL_USER"),
        "PASSWORD": os.getenv("DATABASE_GLOBAL_PASSWORD"),
        "HOST": os.getenv("DATABASE_GLOBAL_HOST"),
        "PORT": os.getenv("DATABASE_GLOBAL_PORT"),
    },
    "bankConn": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DATABASE_BNK"),
        "USER": os.getenv("DATABASE_USER_BNK"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD_BNK"),
        "HOST": os.getenv("DATABASE_HOST_BNK"),
        "PORT": os.getenv("DATABASE_PORT_BNK"),
    },
    "global_local": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DATABASE_GSL"),
        "USER": os.getenv("DATABASE_USER_GSL"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD_GSL"),
        "HOST": os.getenv("DATABASE_HOST_GSL"),
        "PORT": os.getenv("DATABASE_PORT_GSL"),
    },
    "dac": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME_DAC"),
        "USER": os.getenv("DB_USER_DAC"),
        "PASSWORD": os.getenv("DB_PASSWORD_DAC"),
        "HOST": os.getenv("DB_HOST_DAC"),
        "PORT": os.getenv("DB_PORT_DAC"),
    },
    "sdkConn": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME_SDK"),
        "USER": os.getenv("DB_USER_SDK"),
        "PASSWORD": os.getenv("DB_PASSWORD_SDK"),
        "HOST": os.getenv("DB_HOST_SDK"),
        "PORT": os.getenv("DB_PORT_SDK"),
    },
    "super": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME_SUPER"),
        "USER": os.getenv("DB_USER_SUPER"),
        "PASSWORD": os.getenv("DB_PASSWORD_SUPER"),
        "HOST": os.getenv("DB_HOST_SUPER"),
        "PORT": os.getenv("DB_PORT_SUPER"),
    },
    "control_total": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_DATABASE_CT"),
        "USER": os.getenv("DB_USERNAME_CT"),
        "PASSWORD": os.getenv("DB_PASSWORD_CT"),
        "HOST": os.getenv("DB_HOST_CT"),
        "PORT": os.getenv("DB_PORT_CT"),
    },
    "control_total_test": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_DATABASE_CT_T"),
        "USER": os.getenv("DB_USERNAME_CT_T"),
        "PASSWORD": os.getenv("DB_PASSWORD_CT_T"),
        "HOST": os.getenv("DB_HOST_CT_T"),
        "PORT": os.getenv("DB_PORT_CT_T"),
    },
    "universal": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME_UDC"),
        "USER": os.getenv("DB_USER_UDC"),
        "PASSWORD": os.getenv("DB_PASSWORD_UDC"),
        "HOST": os.getenv("DB_HOST_UDC"),
        "PORT": os.getenv("DB_PORT_UDC"),
        "OPTIONS": {
            "local_infile": 1,
        },
    },
    "udc_dev1": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_DATABASE_SDK"),
        "USER": os.getenv("DB_USERNAME_SDK"),
        "PASSWORD": os.getenv("DB_PASSWORD_SDK"),
        "HOST": os.getenv("DB_HOST_SDK"),
        "PORT": os.getenv("DB_PORT_SDK"),
    },
    "contable": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME_CONTA_UDC"),
        "USER": os.getenv("DB_USER_CONTA_UDC"),
        "PASSWORD": os.getenv("DB_PASSWORD_CONTA_UDC"),
        "HOST": os.getenv("DB_HOST_CONTA_UDC"),
        "PORT": os.getenv("DB_PORT_CONTA_UDC"),
        "OPTIONS": {
            "local_infile": 1,
        },
    },
    "activo": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME_AF_UDC"),
        "USER": os.getenv("DB_USER_AF_UDC"),
        "PASSWORD": os.getenv("DB_PASSWORD_AF_UDC"),
        "HOST": os.getenv("DB_HOST_AF_UDC"),
        "PORT": os.getenv("DB_PORT_AF_UDC"),
        "OPTIONS": {
            "local_infile": 1,
        },
    },
    "mastercontrol_EC2": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME_MASTER_CONTROL_EC2"),
        "USER": os.getenv("DB_USER_MASTER_CONTROL_EC2"),
        "PASSWORD": os.getenv("DB_PASSWORD_MASTER_CONTROL_EC2"),
        "HOST": os.getenv("DB_HOST_MASTER_CONTROL_EC2"),
        "PORT": os.getenv("DB_PORT_MASTER_CONTROL_EC2"),
        "OPTIONS": {
            "local_infile": 1,
        },
    },
    "estratega_EC2": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME_ESTRATEGA_EC2"),
        "USER": os.getenv("DB_USER_ESTRATEGA_EC2"),
        "PASSWORD": os.getenv("DB_PASSWORD_ESTRATEGA_EC2"),
        "HOST": os.getenv("DB_HOST_ESTRATEGA_EC2"),
        "PORT": os.getenv("DB_PORT_ESTRATEGA_EC2"),
        "OPTIONS": {
            "local_infile": 1,
        },
    },
    "contable_zeus": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DATABASE_CONTABLE_ZEUS"),
        "USER": os.getenv("DATABASE_USER_CONTABLE_ZEUS"),
        "PASSWORD": os.getenv("DATABASE_PASSWORD_CONTABLE_ZEUS"),
        "HOST": os.getenv("DATABASE_HOST_CONTABLE_ZEUS"),
        "PORT": os.getenv("DATABASE_PORT_CONTABLE_ZEUS"),
    },
    "talento": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME_UDC"),
        "USER": os.getenv("DB_USER_UDC"),
        "PASSWORD": os.getenv("DB_PASSWORD_UDC"),
        "HOST": os.getenv("DB_HOST_UDC"),
        "PORT": os.getenv("DB_PORT_UDC"),
    },
    "superCafe": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME_SUPER_CAFE"),
        "USER": os.getenv("DB_USER_SUPER_CAFE"),
        "PASSWORD": os.getenv("DB_PASSWORD_SUPER_CAFE"),
        "HOST": os.getenv("DB_HOST_SUPER_CAFE"),
        "PORT": os.getenv("DB_PORT_SUPER_CAFE"),
    },
}

DATABASE_ROUTERS = [
    "dacd.routers.Database2Router",
]
USE_TZ = True


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True

SESSION_COOKIE_AGE = 300 * 300  # 1 hora
# SESSION_COOKIE_AGE = 120 # 2 MIN (60 = 1 MIN)
SESSION_SAVE_EVERY_REQUEST = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(
        BASE_DIR, "static"
    ),  # Solo si tienes archivos estáticos fuera de las apps, en una carpeta común
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


SECURITY_PASSWORD_SALT = "cws2024*8520"  # Reemplaza con tu salt secreto real

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.office365.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "notificaciones@carbajalhn.com"
EMAIL_HOST_PASSWORD = "notificacion*2023"
