from django.urls import path
from .views import BancosView
from .views import ConfigView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Panel principal bancario
    path("panel/", BancosView.panel_bancario, name="panel_bancario"),
    # ======================================= CONFIGURACIONES =======================================
    path(
        "configuraciones/destinos-procedencias",
        ConfigView.bancario_config_destinos_procedencias,
        name="bancario_config_destinos_procedencias",
    ),
    path(
        "bk_get_lista_asignaciones",
        ConfigView.bk_get_lista_asignaciones,
        name="bk_get_lista_asignaciones",
    ),
    path(
        "bk_toggle_asignacion",
        ConfigView.bk_toggle_asignacion,
        name="bk_toggle_asignacion",
    ),
    # ======================================= ENLAZAR =======================================
    path(
        "bancario/enlanzar/destinos/procedencias",
        BancosView.bank_enlazar_destinos_procedencias,
        name="bank_enlazar_destinos_procedencias",
    ),
    path(
        "dataEnlacesAdmin",
        BancosView.dataEnlacesAdmin,
        name="dataEnlacesAdmin",
    ),
    path(
        "saveEnlaceDestinoProcedencia",
        BancosView.saveEnlaceDestinoProcedencia,
        name="saveEnlaceDestinoProcedencia",
    ),
    path(
        "toggleEnlaceDestinoProcedencia",
        BancosView.toggleEnlaceDestinoProcedencia,
        name="toggleEnlaceDestinoProcedencia",
    ),
    path(
        "setEnlaceMovimiento",
        BancosView.setEnlaceMovimiento,
        name="setEnlaceMovimiento",
    ),
    path(
        "dataDestinosProcedenciasMovimientos",
        BancosView.dataDestinosProcedenciasMovimientos,
        name="dataDestinosProcedenciasMovimientos",
    ),
    path(
        "dataTiposEnlancesDestinosProcedencias",
        BancosView.dataTiposEnlancesDestinosProcedencias,
        name="dataTiposEnlancesDestinosProcedencias",
    ),
    path(
        "panel/destinos/procedencias/enlazar",
        BancosView.bank_enlazar_destinos_procedencias,
        name="bank_enlazar_destinos_procedencias",
    ),
    path(
        "api/caja/salidas/pendientes",
        BancosView.api_get_caja_salidas_pendientes,
        name="api_get_caja_salidas_pendientes",
    ),
    # ======================================= CAJA / LIQUIDACION =======================================
    path(
        "bank/liquidacion/caja/turnos",
        BancosView.bank_liquidacion_caja_turnos,
        name="bank_liquidacion_caja_turnos",
    ),
    path(
        "getDataTurnosLiquidar",
        BancosView.getDataTurnosLiquidar,
        name="getDataTurnosLiquidar",
    ),
    path(
        "getDataLiquidacionMovDiario",
        BancosView.getDataLiquidacionMovDiario,
        name="getDataLiquidacionMovDiario",
    ),
    path(
        "actualizar_turno_liquidacion",
        BancosView.actualizar_turno_liquidacion,
        name="actualizar_turno_liquidacion",
    ),
    # ======================================= ANTICIPOS CLIENTES =======================================
    path(
        "bancario/listado/anticipo/clientes",
        BancosView.listado_anticipo_clientes,
        name="listado_anticipo_clientes",
    ),
    path(
        "bk_get_lote_abonos_listado",
        BancosView.bk_get_lote_abonos_listado,
        name="bk_get_lote_abonos_listado",
    ),
    path(
        "bk_autorizar_abonos_detalle",
        BancosView.bk_autorizar_abonos_detalle,
        name="bk_autorizar_abonos_detalle",
    ),
    path(
        "bk_get_abonos_por_autorizacion",
        BancosView.bk_get_abonos_por_autorizacion,
        name="bk_get_abonos_por_autorizacion",
    ),
    path(
        "bk_get_lotes_autorizados",
        BancosView.bk_get_lotes_autorizados,
        name="bk_get_lotes_autorizados",
    ),
    path(
        "bk_get_detalle_lote_aut",
        BancosView.bk_get_detalle_lote_aut,
        name="bk_get_detalle_lote_aut",
    ),
    path(
        "bk_descargar_anticipos_clientes_autorizados",
        BancosView.bk_descargar_anticipos_clientes_autorizados,
        name="bk_descargar_anticipos_clientes_autorizados",
    ),
    path(
        "bancario/crear/anticipo/clientes",
        BancosView.crear_anticipo_clientes,
        name="crear_anticipo_clientes",
    ),
    path(
        "get_cxc_pendientes_cliente",
        BancosView.get_cxc_pendientes_cliente,
        name="get_cxc_pendientes_cliente",
    ),
    path(
        "bank_guardar_lote_abonos",
        BancosView.bank_guardar_lote_abonos,
        name="bank_guardar_lote_abonos",
    ),
    # ======================================= MOVIMIENTOS BANCARIOS =======================================
    path(
        "validar_mes_movimiento",
        BancosView.validar_mes_movimiento,
        name="validar_mes_movimiento",
    ),
    path(
        "bancario/crear/movimiento/credito",
        BancosView.crear_movimiento_credito,
        name="crear_movimiento_credito",
    ),
    path(
        "guardar_movimiento_credito",
        BancosView.guardar_movimiento_credito,
        name="guardar_movimiento_credito",
    ),
    path(
        "bancario/crear/movimiento/debito",
        BancosView.crear_movimiento_debito,
        name="crear_movimiento_debito",
    ),
    path(
        "saveMovimientoBancarioDebito",
        BancosView.saveMovimientoBancarioDebito,
        name="saveMovimientoBancarioDebito",
    ),
    path(
        "get_cuentas_bancarias",
        BancosView.get_cuentas_bancarias,
        name="get_cuentas_bancarias",
    ),
    path(
        "api_get_sucursales_usuario",
        BancosView.api_get_sucursales_usuario,
        name="api_get_sucursales_usuario",
    ),
    path(
        "api_get_ingresos_pendientes",
        BancosView.api_get_ingresos_pendientes,
        name="api_get_ingresos_pendientes",
    ),
    path(
        "api_get_solicitudes_acreedor",
        BancosView.api_get_solicitudes_acreedor,
        name="api_get_solicitudes_acreedor",
    ),
    path(
        "api_get_saldo_cuenta",
        BancosView.api_get_saldo_cuenta,
        name="api_get_saldo_cuenta",
    ),
    path(
        "get_movimientos_caja_liquidaciones",
        BancosView.get_movimientos_caja_liquidaciones,
        name="get_movimientos_caja_liquidaciones",
    ),
    # ======================================= TASA DE SEGURIDAD =======================================
    path(
        "calcular_tasa_seguridad",
        BancosView.calcular_tasa_seguridad,
        name="calcular_tasa_seguridad",
    ),
    path(
        "calcular_tasa_seguridad_multi",
        BancosView.calcular_tasa_seguridad_multi,
        name="calcular_tasa_seguridad_multi",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
