<?php
    /*
    TODO:

        * PRIORIDAD REPORTES DE LAS CORRECIONES QUE ENVIO JORGE

        * OPCION DE PODER CREAR CUENTA CONTABLE PARA TODOS LOS CENTROS
                -- CUENTA NUEVA BENEFICIO DE EMPLEADOS
                MERA LIBERALIDAD
                '001-019'
        
        * CREAR EMPLEADO OBLIGATORIO CUENTA CONTABLE

        
        * FORMULAS PARA CALCULO DE BALANZA DE COMPROBACION X CLASE DE CUENTAS
            ! SALDO INICIAL + DEBE - HABER = SALDO FINAL PARA TODAS

            1
            SALDO INICAL + DEBE - HABER = SALDO FINAL

            2
            SALDO INICIAL + HABER - DEBE = SALDO FINAL

            3
            SALDO INICIAL + HABER - DEBE = SALDO FINAL

            4
            SALDO INICIAL + HABER - DEBE = SALDO FINAL

            5
            SALDO INICAL + DEBE - HABER = SALDO FINAL

            6
            SALDO INICAL + DEBE - HABER = SALDO FINAL

            7
            SALDO INICIAL + HABER - DEBE = SALDO FINAL

            8
            SALDO INICAL + DEBE - HABER = SALDO FINAL

            9
            SALDO INICAL + DEBE - HABER = SALDO FINAL
            
            



        
        * BON, DED, Y COMISIONES OBLIGATORIO ASIGNARC CUENTA CONTABLE O SI APLICA X CENTRO Y AGG EL CAMPO DE MOTIVO O DESCRIPCION

        * TIPO DE PLANILLA VA A TENER UN TIPO DE PARTIDA DIFERENTE

        * AL SELCCIONAR LAS CUENTAS X EMPLEADOS DEBE VERSE TODA LA CUENTA CONTABLE COMPLETA 15 CARACTERES
          *   EN VEZ DE SELECCIONAR TODA LA CUENTA, SOLO PONER LA CUENTA CORTA

        * AL APLICAR PLANILLA VALIDAR QUE TODOS LOS EMPLEADOS TENGAN CUENTA, BONIFICACIONES, COMISIONES Y DEDUCCIONES Y UN RESUMEN PARA QUE SEPAN QUE FALTA

        * PARTIDAS MANUALES VER SOLO CUENTAS DE GRADO 15


        * PLANILLA
            AL APLICAR LA PLANILLA SE DEBE REFLEJAR EN EL PRESUPUESTO


        * BON, DED Y COMISIONES PONER BUSCADOR DE CUENTA

        * FORMULARIO PARA TIPO DE PLANILLA CAMPO DE CUENTA CONTABLE O TOMA LA DEL EMPLEADO Y SI APLICA A GASTO
            TIPO DE PLANILLA -> TIENE CUENTA CONTABLE X EMPLEADO, TIENE CUENTA CONTABLE GENERAL, CUENTA SE ASIGNA EN PARTIDA CONTABLE
            CAMPO DE REGISTRAR CAMPO APLICA/NO APLICA
            

        * INTERFAZ DE CONFIGURACION DE VALORES DE CONTABILIDAD
            HISTORICO DE VALORES, ES DECIR, SE GUARDA EL VALOR VIEJO AL EDITAR


        * APARTADO DEDUCCIONES POR LEY
            RAP 1/0
            IHSS 1/0

            Y A LOS EMPLEADOS QUE APLICAN ESAS COSAS SE LES HARA EL CALCULO PARA LA PARTIDA DE PLANILLA

        * INFOP ES PARA TODOS Y SE CALCULA X EL VALOR DE LA PLANILLA DE SUELDOS Y SALARIOS DE X PARTIDA, X PARTIDA DE FORMA QUINCENAL EN ESTE CASO
        
        * TALENTO HUMANO FILTROS PARA TRAER ASISTENCIAS X DEPARTAMENTOS O X EMPLEADOS

                   
        * PARTIDA DE GASTOS PATRONALES INCLUIDOS EN PARTIDA DE REGISTRO DE GASTOS X EMPLEADOS SI APLICA A IHSS Y RAP, INFOP APLICA A TODOS
            IHSS, INFOP Y RAP


            
        * PARTIDA PATRONAL APLICA X EMPLEADO, INFOP X EMPRESA VALOR SE TOMA DE SALARIO
            INFOP X 1%
            
            IHSS EMPLEADO SE CALCULA POR
                TOPE * PORC (8.7)
                    AL HABER ES LA SUMATORIA DE TODOS

            RAP ES PORC 0
            
            INFOP SE CONFIGURA DESDE LA EMPRESA EN EL CATALOGO


        * PROVISIONES
        PARA EMPLEADO X CONTRATO INDEFINIDO

        (SALARIO / 12)  = CALCULO DE PROVISION DIARIO
        
        13VO
        14VO
        CESANTIA        = ((SALARIO * 14) / 360) * 30

        * CALCULO PARA TODOS
        PREAVISO        =
            2m  = 0
            3m  = 24h
            6m  = 7d
            1y  = 15d
            2y  = 1m
            2y+ = 2m

        * CALCULO X CONTRATO INDEFINIDO Y ES SALARIO X DIA
        VACACIONES      =   
            1y  = 10d
            2y  = 12d
        
    


        * LIBRO DIARIO
            SUCURSAL

        * EXONERADA
            HAY UN CHECK ES EXONERADA Y ENTONCES SI ESTA ESE CHECK, SE IRA TODO PARA AHI

        * COMPRAS
            LAS CUENTAS DE 18 Y 15 CRUZADA


        * ELIMINAR TODAS LAS COMPRAS, LAS DE VENTAS CONTADO Y CREDITO



        * FORMULARIO PARA PARAMETRIZAR TODO ESTO
            PREAVISO        =
                2m  = 0
                3m  = 24h
                6m  = 7d
                1y  = 15d
                2y  = 1m
                2y+ = 2m



        * REPORTE INTEGRACION DE CUENTAS CONTABLES


        * ESTRUCTURA DE PARTIDA MARCAR COMO REVISADA Y AL ESTAR ESO NO PUEDEN AGG COSAS O QUITAR

        * PARTIDAS DE COSTOS


        * FORMULARIO PARA CLASIFICAR MOVIMIENTOS BANCARIOS POR DESTINOS O PROCEDENCIAS CLASIFICADOS X CUENTA
        
        * RE FORMULAR PARTIDAS DE VENTA CONTADO, CREDITO, COSTOS Y COMPRAS POR SUCURSAL

        * OPCION DE PODER CARGAR MASIVAMENTE LOS DESTINOS Y PROCEDENCIAS PARA ACTUALIZARLOS







        ? PENDIENTES























        ! ANOTACIONES

 
        EMPRESAS QUE TIENE ACCESO, ACCESO A X SUCURSAL
        


    */





?>