from django.urls import path
from .views import ContableView, CtrlGestionView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("panel/", ContableView.panel_contabilidad, name="panel_contabilidad"),
    path(
        "panel/clasificacion/cuentas",
        ContableView.conta_clasificacion_cuentas,
        name="conta_clasificacion_cuentas",
    ),
    path(
        "panel/clasificacion/cuentas/nic",
        ContableView.conta_clasificacion_cuentas_nic,
        name="conta_clasificacion_cuentas_nic",
    ),
    path("panel/cuentas/nic", ContableView.cuentas_nic, name="cuentas_nic"),
    path(
        "panel/partidas/contables",
        ContableView.catalogo_partidas_contables,
        name="catalogo_partidas_contables",
    ),
    path(
        "panel/generar/partidas",
        ContableView.conta_generar_partidas_view,
        name="conta_generar_partidas_view",
    ),
    path(
        "panel/balaza/comprobacion",
        ContableView.conta_balanza_de_comprobacion,
        name="conta_balanza_de_comprobacion",
    ),
    path(
        "dataBalanzaComprobacion",
        ContableView.dataBalanzaComprobacion,
        name="dataBalanzaComprobacion",
    ),
    path("panel/firmas/financieras", ContableView.firmas_view, name="firmas_view"),
    path(
        "dataFirmasFinancieras",
        ContableView.dataFirmasFinancieras,
        name="dataFirmasFinancieras",
    ),
    path("insert_new_firma", ContableView.insert_new_firma, name="insert_new_firma"),
    path(
        "insert_update_firma_empresa",
        ContableView.insert_update_firma_empresa,
        name="insert_update_firma_empresa",
    ),
    path(
        "update_status_firmas",
        ContableView.update_status_firmas,
        name="update_status_firmas",
    ),
    path(
        "get_tipos_firmas_numeracion",
        ContableView.get_tipos_firmas_numeracion,
        name="get_tipos_firmas_numeracion",
    ),
    path(
        "exportMovimientosDestinosProcedenciasExcel",
        ContableView.exportMovimientosDestinosProcedenciasExcel,
        name="exportMovimientosDestinosProcedenciasExcel",
    ),
    path(
        "cargarExcelEnlacesDestinosProcedencias",
        ContableView.cargarExcelEnlacesDestinosProcedencias,
        name="cargarExcelEnlacesDestinosProcedencias",
    ),
    path(
        "api/guardar_saldo_manual_bg/",
        ContableView.guardarSaldoManualBG,
        name="guardarSaldoManualBG",
    ),
    path("dataTiposPartidas", ContableView.dataTiposPartidas, name="dataTiposPartidas"),
    path(
        "dataDetallesTiposPartidas",
        ContableView.dataDetallesTiposPartidas,
        name="dataDetallesTiposPartidas",
    ),
    path(
        "dataClasificacionCuentas",
        ContableView.dataClasificacionCuentas,
        name="dataClasificacionCuentas",
    ),
    path("dataCuentasNIC", ContableView.dataCuentasNIC, name="dataCuentasNIC"),
    path(
        "dataCuentasDisponiblesNIC",
        ContableView.dataCuentasDisponiblesNIC,
        name="dataCuentasDisponiblesNIC",
    ),
    path(
        "dataCuentasAsociadasNIC",
        ContableView.dataCuentasAsociadasNIC,
        name="dataCuentasAsociadasNIC",
    ),
    path(
        "dataTiposClasesCuentas",
        ContableView.dataTiposClasesCuentas,
        name="dataTiposClasesCuentas",
    ),
    path(
        "dataCuentasContables",
        ContableView.dataCuentasContables,
        name="dataCuentasContables",
    ),
    path(
        "update_status_cuentas_contables",
        ContableView.update_status_cuentas_contables,
        name="update_status_cuentas_contables",
    ),
    path(
        "cuentas_contables/", ContableView.cuentas_contables, name="cuentas_contables"
    ),
    path(
        "obtener_subcuentas/",
        ContableView.obtener_subcuentas,
        name="obtener_subcuentas",
    ),
    path("generar_codigo/", ContableView.generar_codigo, name="generar_codigo"),
    path(
        "insertar_actualizar_cuenta/",
        ContableView.insertar_actualizar_cuenta,
        name="insertar_actualizar_cuenta",
    ),
    path(
        "conta_update_es_cuenta_padre",
        ContableView.conta_update_es_cuenta_padre,
        name="conta_update_es_cuenta_padre",
    ),
    path(
        "insert_update_tipos_partidas",
        ContableView.insert_update_tipos_partidas,
        name="insert_update_tipos_partidas",
    ),
    path(
        "update_status_tipos_partidas",
        ContableView.update_status_tipos_partidas,
        name="update_status_tipos_partidas",
    ),
    path(
        "insert_update_detalles_tipos_partidas",
        ContableView.insert_update_detalles_tipos_partidas,
        name="insert_update_detalles_tipos_partidas",
    ),
    path(
        "update_status_detalle_tipos_partidas",
        ContableView.update_status_detalle_tipos_partidas,
        name="update_status_detalle_tipos_partidas",
    ),
    path(
        "insert_update_clasificacion_cuentas",
        ContableView.insert_update_clasificacion_cuentas,
        name="insert_update_clasificacion_cuentas",
    ),
    path(
        "update_status_clasificacion_cuentas",
        ContableView.update_status_clasificacion_cuentas,
        name="update_status_clasificacion_cuentas",
    ),
    path(
        "insert_remove_cuenta_x_nic",
        ContableView.insert_remove_cuenta_x_nic,
        name="insert_remove_cuenta_x_nic",
    ),
    path(
        "insert_update_cuenta_nic",
        ContableView.insert_update_cuenta_nic,
        name="insert_update_cuenta_nic",
    ),
    path(
        "update_status_cuentas_nic",
        ContableView.update_status_cuentas_nic,
        name="update_status_cuentas_nic",
    ),
    path(
        "panel/configuraciones/contables",
        ContableView.conta_configuraciones_contables,
        name="conta_configuraciones_contables",
    ),
    path(
        "dataConfiguraciones",
        ContableView.dataConfiguraciones,
        name="dataConfiguraciones",
    ),
    path(
        "dataConfiguracionesHistorico",
        ContableView.dataConfiguracionesHistorico,
        name="dataConfiguracionesHistorico",
    ),
    path(
        "conta_insert_update_configuraciones",
        ContableView.conta_insert_update_configuraciones,
        name="conta_insert_update_configuraciones",
    ),
    path(
        "conta_update_status_configuraciones",
        ContableView.conta_update_status_configuraciones,
        name="conta_update_status_configuraciones",
    ),
    path(
        "dataProvisionesDetalleEmpresa",
        ContableView.dataProvisionesDetalleEmpresa,
        name="dataProvisionesDetalleEmpresa",
    ),
    path("panel/cuentas/gastos", ContableView.cuentas_gastos, name="cuentas_gastos"),
    path("dataCuentasGastos", ContableView.dataCuentasGastos, name="dataCuentasGastos"),
    path(
        "insert_update_cuentas_gastos",
        ContableView.insert_update_cuentas_gastos,
        name="insert_update_cuentas_gastos",
    ),
    path(
        "update_status_cuentas_gastos",
        ContableView.update_status_cuentas_gastos,
        name="update_status_cuentas_gastos",
    ),
    path(
        "conta_update_es_padre_cuentas_gastos",
        ContableView.conta_update_es_padre_cuentas_gastos,
        name="conta_update_es_padre_cuentas_gastos",
    ),
    path("dataCentrosCosto", ContableView.dataCentrosCosto, name="dataCentrosCosto"),
    path(
        "dataOrdenesComprasIngresadas",
        ContableView.dataOrdenesComprasIngresadas,
        name="dataOrdenesComprasIngresadas",
    ),
    path(
        "dataHistorialCierres",
        ContableView.dataHistorialCierres,
        name="dataHistorialCierres",
    ),
    path(
        "realizar_cierre_mes",
        ContableView.realizar_cierre_mes,
        name="realizar_cierre_mes",
    ),
    path(
        "actualizar_estado_cierre_contable",
        ContableView.actualizar_estado_cierre_contable,
        name="actualizar_estado_cierre_contable",
    ),
    path(
        "entregar_periodo_contable",
        ContableView.entregar_periodo_contable,
        name="entregar_periodo_contable",
    ),
    path(
        "actualizar_saldos_contables_mes",
        ContableView.actualizar_saldos_contables_mes,
        name="actualizar_saldos_contables_mes",
    ),
    path(
        "get_saldos_contables_mes",
        ContableView.get_saldos_contables_mes,
        name="get_saldos_contables_mes",
    ),
    path(
        "panel/contabilidad/calendario",
        ContableView.conta_calendario_contable,
        name="conta_calendario_contable",
    ),
    path(
        "load_calendario_contable",
        ContableView.load_calendario_contable,
        name="load_calendario_contable",
    ),
    path(
        "guardar_fecha_calendario",
        ContableView.guardar_fecha_calendario,
        name="guardar_fecha_calendario",
    ),
    path(
        "panel/contabilidad/partida/manual/<int:partida>",
        ContableView.conta_new_edit_partida,
        name="conta_new_edit_partida",
    ),
    path(
        "panel/contabilidad/partidas/descuadradas",
        ContableView.conta_partidas_descuadradas,
        name="conta_partidas_descuadradas",
    ),
    path(
        "dataPartidasDescuadradas",
        ContableView.dataPartidasDescuadradas,
        name="dataPartidasDescuadradas",
    ),
    path(
        "list_all_cuentas_grado",
        ContableView.list_all_cuentas_grado,
        name="list_all_cuentas_grado",
    ),
    path(
        "panel/contabilidad/libro/diario",
        ContableView.conta_libro_diario,
        name="conta_libro_diario",
    ),
    path("dataLibroDiario", ContableView.dataLibroDiario, name="dataLibroDiario"),
    path(
        "dataDetallesPartidasAutomaticas",
        ContableView.dataDetallesPartidasAutomaticas,
        name="dataDetallesPartidasAutomaticas",
    ),
    path(
        "update_status_partida",
        ContableView.update_status_partida,
        name="update_status_partida",
    ),
    path(
        "panel/contabilidad/meses/cerrados/entregados",
        ContableView.conta_meses_cerrados_entregados,
        name="conta_meses_cerrados_entregados",
    ),
    path(
        "dataMesesCerradosEntregados",
        ContableView.dataMesesCerradosEntregados,
        name="dataMesesCerradosEntregados",
    ),
    path(
        "update_status_meses_cerrados",
        ContableView.update_status_meses_cerrados,
        name="update_status_meses_cerrados",
    ),
    path(
        "update_meses_cerrados",
        ContableView.update_meses_cerrados,
        name="update_meses_cerrados",
    ),
    path(
        "panel/contabilidad/actualizar/datos/mes",
        ContableView.conta_actualizar_datos_mes,
        name="conta_actualizar_datos_mes",
    ),
    path(
        "get_codigo_cuenta_x_fecha",
        ContableView.get_codigo_cuenta_x_fecha,
        name="get_codigo_cuenta_x_fecha",
    ),
    path(
        "anular_cierre_cuenta_mes",
        ContableView.anular_cierre_cuenta_mes,
        name="anular_cierre_cuenta_mes",
    ),
    path(
        "get_datos_cierre_anterior",
        ContableView.get_datos_cierre_anterior,
        name="get_datos_cierre_anterior",
    ),
    path(
        "get_saldos_cuenta_x_nic",
        ContableView.get_saldos_cuenta_x_nic,
        name="get_saldos_cuenta_x_nic",
    ),
    path(
        "insert_cierre_cuenta_mes",
        ContableView.insert_cierre_cuenta_mes,
        name="insert_cierre_cuenta_mes",
    ),
    path(
        "panel/contabilidad/cierre/entrega/mes",
        ContableView.conta_cierre_entrega_mes,
        name="conta_cierre_entrega_mes",
    ),
    path(
        "get_ultimo_mes_anio_from_meses_cerrados",
        ContableView.get_ultimo_mes_anio_from_meses_cerrados,
        name="get_ultimo_mes_anio_from_meses_cerrados",
    ),
    path(
        "insert_update_meses_cerrados",
        ContableView.insert_update_meses_cerrados,
        name="insert_update_meses_cerrados",
    ),
    path(
        "obtener_nombre_mes", ContableView.obtener_nombre_mes, name="obtener_nombre_mes"
    ),
    path(
        "get_meses_cerrados_estado_cerrado",
        ContableView.get_meses_cerrados_estado_cerrado,
        name="get_meses_cerrados_estado_cerrado",
    ),
    path(
        "obtener_datos_para_cierre_mes",
        ContableView.obtener_datos_para_cierre_mes,
        name="obtener_datos_para_cierre_mes",
    ),
    path(
        "panel/contabilidad/partida/manual/<int:partida>/<int:empresa>",
        ContableView.conta_new_edit_partida,
        name="conta_new_edit_partida",
    ),
    path(
        "insert_update_partidas_header_details",
        ContableView.insert_update_partidas_header_details,
        name="insert_update_partidas_header_details",
    ),
    path(
        "get_tasa_cambio_x_fecha",
        ContableView.get_tasa_cambio_x_fecha,
        name="get_tasa_cambio_x_fecha",
    ),
    path("panel/tasa/cambio", ContableView.conta_tasa_cambio, name="conta_tasa_cambio"),
    path("dataTasaCambio", ContableView.dataTasaCambio, name="dataTasaCambio"),
    path(
        "insert_update_tasa_cambio",
        ContableView.insert_update_tasa_cambio,
        name="insert_update_tasa_cambio",
    ),
    path(
        "update_status_tasa_cambio",
        ContableView.update_status_tasa_cambio,
        name="update_status_tasa_cambio",
    ),
    path(
        "panel/flujo/efectivo/cuentas",
        ContableView.conta_flujo_efectivo,
        name="conta_flujo_efectivo",
    ),
    path("dataFlujoEfectivo", ContableView.dataFlujoEfectivo, name="dataFlujoEfectivo"),
    path(
        "panel/diferencia/cambio",
        ContableView.conta_diferencia_cambio,
        name="conta_diferencia_cambio",
    ),
    path(
        "panel/secuencia/partidas",
        ContableView.conta_secuencia_partidas,
        name="conta_secuencia_partidas",
    ),
    path(
        "dataDifCambioResumen",
        ContableView.dataDifCambioResumen,
        name="dataDifCambioResumen",
    ),
    path(
        "dataSecuenciaPartidas",
        ContableView.dataSecuenciaPartidas,
        name="dataSecuenciaPartidas",
    ),
    path(
        "get_tasa_cambio_hoy",
        ContableView.get_tasa_cambio_hoy,
        name="get_tasa_cambio_hoy",
    ),
    path(
        "panel/balance/general",
        ContableView.conta_balance_general,
        name="conta_balance_general",
    ),
    path(
        "dataBalanceGeneral", ContableView.dataBalanceGeneral, name="dataBalanceGeneral"
    ),
    path(
        "panel/auxiliar/cuentas/<int:empresa>",
        ContableView.conta_auxiliar_cuentas,
        name="conta_auxiliar_cuentas",
    ),
    path(
        "panel/libro/mayor/<int:empresa>",
        ContableView.conta_libro_mayor,
        name="conta_libro_mayor",
    ),
    path("dataLibroMayor", ContableView.dataLibroMayor, name="dataLibroMayor"),
    path(
        "panel/asignar/cuentas/movimientos",
        ContableView.conta_asignar_cuentas_movimientos,
        name="conta_asignar_cuentas_movimientos",
    ),
    path(
        "dataCuentasAsignadas",
        ContableView.dataCuentasAsignadas,
        name="dataCuentasAsignadas",
    ),
    path(
        "insert_cuenta_tipo_movimiento",
        ContableView.insert_cuenta_tipo_movimiento,
        name="insert_cuenta_tipo_movimiento",
    ),
    path(
        "update_status_cuenta_tipo_movimiento",
        ContableView.update_status_cuenta_tipo_movimiento,
        name="update_status_cuenta_tipo_movimiento",
    ),
    path(
        "dataEstructuraTipoPartida",
        ContableView.dataEstructuraTipoPartida,
        name="dataEstructuraTipoPartida",
    ),
    path(
        "get/cuentas/tipos/movimientos/asignados",
        ContableView.API_cuentas_asignadas_x_movimiento,
        name="API_cuentas_asignadas_x_movimiento",
    ),
    path(
        "panel/entregar/periodo/<int:empresa>",
        ContableView.conta_entregar_periodos,
        name="conta_entregar_periodos",
    ),
    path(
        "autorizar_entregar_periodos",
        ContableView.autorizar_entregar_periodos,
        name="autorizar_entregar_periodos",
    ),
    path(
        "generar_partida_entregar_periodo",
        ContableView.generar_partida_entregar_periodo,
        name="generar_partida_entregar_periodo",
    ),
    path("logoutRequest", ContableView.logoutRequest, name="logoutRequest"),
    path(
        "obtener_cuentas_ordenadas",
        ContableView.obtener_cuentas_ordenadas,
        name="obtener_cuentas_ordenadas",
    ),
    path(
        "obtener_partida_completa",
        ContableView.obtener_partida_completa,
        name="obtener_partida_completa",
    ),
    path(
        "get_estado_calendario_dashboard",
        ContableView.get_estado_calendario_dashboard,
        name="get_estado_calendario_dashboard",
    ),
    path(
        "get_partidas_descuadradas_dashboard",
        ContableView.get_partidas_descuadradas_dashboard,
        name="get_partidas_descuadradas_dashboard",
    ),
    path(
        "dataSolicitudGasto", ContableView.dataSolicitudGasto, name="dataSolicitudGasto"
    ),
    path(
        "dataSolicitudIngreso",
        ContableView.dataSolicitudIngreso,
        name="dataSolicitudIngreso",
    ),
    path(
        "dataPartidasHermanasAsignadas",
        ContableView.dataPartidasHermanasAsignadas,
        name="dataPartidasHermanasAsignadas",
    ),
    path(
        "download_data_partidas_libro_diario",
        ContableView.download_data_partidas_libro_diario,
        name="download_data_partidas_libro_diario",
    ),
    path(
        "download_data_partidas_descuadradas_libro_diario",
        ContableView.download_data_partidas_descuadradas_libro_diario,
        name="download_data_partidas_descuadradas_libro_diario",
    ),
    path(
        "contable/saldos/iniciales/gestion",
        ContableView.conta_saldos_iniciales_lotes,
        name="conta_saldos_iniciales_lotes",
    ),
    path(
        "conta_saldo_lote_upload_excel",
        ContableView.conta_saldo_lote_upload_excel,
        name="conta_saldo_lote_upload_excel",
    ),
    path(
        "conta_saldos_iniciales_descargar_plantilla",
        ContableView.conta_saldos_iniciales_descargar_plantilla,
        name="conta_saldos_iniciales_descargar_plantilla",
    ),
    path(
        "conta_saldo_lote_procesar",
        ContableView.conta_saldo_lote_procesar,
        name="conta_saldo_lote_procesar",
    ),
    path(
        "conta_saldo_lote_editar",
        ContableView.conta_saldo_lote_editar,
        name="conta_saldo_lote_editar",
    ),
    path(
        "conta_saldo_lote_eliminar",
        ContableView.conta_saldo_lote_eliminar,
        name="conta_saldo_lote_eliminar",
    ),
    path(
        "conta_saldo_lote_detalle",
        ContableView.conta_saldo_lote_detalle,
        name="conta_saldo_lote_detalle",
    ),
    path("conta_lote_nuevo", ContableView.conta_lote_nuevo, name="conta_lote_nuevo"),
    path(
        "conta_lotes_listar", ContableView.conta_lotes_listar, name="conta_lotes_listar"
    ),
    path(
        "contable/reporte/estado/resultados/sucursal",
        ContableView.conta_reporte_estado_resultados_sucursal,
        name="conta_reporte_estado_resultados_sucursal",
    ),
    path(
        "generar_partidas_automaticas_movimientos_bancarios",
        ContableView.generar_partidas_automaticas_movimientos_bancarios,
        name="generar_partidas_automaticas_movimientos_bancarios",
    ),
    path(
        "generar_partidas_automaticas_movimientos_bancarios_detalles",
        ContableView.generar_partidas_automaticas_movimientos_bancarios_detalles,
        name="generar_partidas_automaticas_movimientos_bancarios_detalles",
    ),
    path(
        "dataReporteERPorSucursal",
        ContableView.dataReporteERPorSucursal,
        name="dataReporteERPorSucursal",
    ),
    path(
        "contable/clientes/auxiliar",
        ContableView.conta_auxiliar_clientes,
        name="conta_auxiliar_clientes",
    ),
    path(
        "dataAuxiliarClientes",
        ContableView.dataAuxiliarClientes,
        name="dataAuxiliarClientes",
    ),
    path(
        "contable/clientes/saldos/antiguedad",
        ContableView.conta_antiguedad_saldos_clientes,
        name="conta_antiguedad_saldos_clientes",
    ),
    path("dataAgingClientes", ContableView.dataAgingClientes, name="dataAgingClientes"),
    path(
        "contable/proveedores/auxiliar",
        ContableView.conta_auxiliar_proveedores,
        name="conta_auxiliar_proveedores",
    ),
    path(
        "dataAuxiliarProveedores",
        ContableView.dataAuxiliarProveedores,
        name="dataAuxiliarProveedores",
    ),
    path(
        "contable/proveedores/saldos/antiguedad",
        ContableView.conta_antiguedad_saldos_proveedores,
        name="conta_antiguedad_saldos_proveedores",
    ),
    path(
        "dataAgingProveedores",
        ContableView.dataAgingProveedores,
        name="dataAgingProveedores",
    ),
    path(
        "contable/libro/ventas",
        ContableView.conta_libro_ventas,
        name="conta_libro_ventas",
    ),
    path("dataLibroVentas", ContableView.dataLibroVentas, name="dataLibroVentas"),
    path(
        "contable/libro/compras",
        ContableView.conta_libro_compras,
        name="conta_libro_compras",
    ),
    path("dataLibroCompras", ContableView.dataLibroCompras, name="dataLibroCompras"),
    path(
        "contable/estado/resultado",
        ContableView.conta_estado_resultado,
        name="conta_estado_resultado",
    ),
    path(
        "dataEstadoResultado",
        ContableView.dataEstadoResultado,
        name="dataEstadoResultado",
    ),
    path(
        "dataEstadoResultadoDetalle",
        ContableView.dataEstadoResultadoDetalle,
        name="dataEstadoResultadoDetalle",
    ),
    path(
        "contable/auditoria/asientos/cuentas/inactivas",
        ContableView.conta_asiento_cuentas_inactivas,
        name="conta_asiento_cuentas_inactivas",
    ),
    path(
        "dataCuentasInactivas",
        ContableView.dataCuentasInactivas,
        name="dataCuentasInactivas",
    ),
    path(
        "contable/reportes/integracion/cuentas/contables",
        ContableView.conta_reporte_ingregracion_cuentas,
        name="conta_reporte_ingregracion_cuentas",
    ),
    path(
        "dataReporteIntegracionCuentasContables",
        ContableView.dataReporteIntegracionCuentasContables,
        name="dataReporteIntegracionCuentasContables",
    ),
    path(
        "contable/auditoria/meses/abiertos",
        ContableView.conta_meses_abiertos,
        name="conta_meses_abiertos",
    ),
    path("dataMesesAbiertos", ContableView.dataMesesAbiertos, name="dataMesesAbiertos"),
    #           """ ======================================= DATA PARA GENERAR PARTIDAS ======================================= """
    path(
        "dataMovBancariosDetalles",
        ContableView.dataMovBancariosDetalles,
        name="dataMovBancariosDetalles",
    ),
    path(
        "dataDepositosVentas",
        ContableView.dataDepositosVentas,
        name="dataDepositosVentas",
    ),
    path("dataDevoluciones", ContableView.dataDevoluciones, name="dataDevoluciones"),
    path("dataFacturasCosto", ContableView.dataFacturasCosto, name="dataFacturasCosto"),
    path("dataFacturas", ContableView.dataFacturas, name="dataFacturas"),
    path("dataDevolDetalles", ContableView.dataDevolDetalles, name="dataDevolDetalles"),
    path(
        "dataFacturasDetalles",
        ContableView.dataFacturasDetalles,
        name="dataFacturasDetalles",
    ),
    path(
        "dataFacturasDetallesCosto",
        ContableView.dataFacturasDetallesCosto,
        name="dataFacturasDetallesCosto",
    ),
    path(
        "dataOrdenesComprasDetallesIngresadas",
        ContableView.dataOrdenesComprasDetallesIngresadas,
        name="dataOrdenesComprasDetallesIngresadas",
    ),
    #           """ ======================================= FX GENERAR PARTIDAS ======================================= """
    path(
        "generar_partidas_automaticas_devol",
        ContableView.generar_partidas_automaticas_devol,
        name="generar_partidas_automaticas_devol",
    ),
    path(
        "generar_partidas_automaticas_devoluciones",
        ContableView.generar_partidas_automaticas_devoluciones,
        name="generar_partidas_automaticas_devoluciones",
    ),
    path(
        "generar_partidas_automaticas_costos",
        ContableView.generar_partidas_automaticas_costos,
        name="generar_partidas_automaticas_costos",
    ),
    path(
        "generar_partidas_automaticas_ventas",
        ContableView.generar_partidas_automaticas_ventas,
        name="generar_partidas_automaticas_ventas",
    ),
    path(
        "generar_partidas_automaticas_compras",
        ContableView.generar_partidas_automaticas_compras,
        name="generar_partidas_automaticas_compras",
    ),
    path(
        "generar_partidas_automaticas_provisionales",
        ContableView.generar_partidas_automaticas_provisionales,
        name="generar_partidas_automaticas_provisionales",
    ),
    #           """ ======================================= CONTROL DE GESTION ======================================= """
    path("centros", CtrlGestionView.ctrl_centros, name="ctrl_centros"),
    path(
        "gestion/centro/<int:centro_id>/<int:mes>/<int:anio>",
        CtrlGestionView.ctrl_gestion_centro,
        name="ctrl_gestion_centro",
    ),
    path(
        "crear/solicitud/gasto",
        CtrlGestionView.ctrl_crear_solicitud_gasto,
        name="ctrl_crear_solicitud_gasto",
    ),
    path(
        "crear/solicitud/ingreso",
        CtrlGestionView.ctrl_crear_solicitud_ingreso,
        name="ctrl_crear_solicitud_ingreso",
    ),
    path(
        "ingresar/gastos/bancario",
        CtrlGestionView.ctrl_ingresar_gastos_bancario,
        name="ctrl_ingresar_gastos_bancario",
    ),
    path(
        "reporteria/balance/presupuesto/centros",
        CtrlGestionView.ctrl_balance_presupuesto_centros_view,
        name="ctrl_balance_presupuesto_centros_view",
    ),
    path(
        "reporteria/balance/presupuesto/cuentas",
        CtrlGestionView.ctrl_balance_presupuesto_cuentas_view,
        name="ctrl_balance_presupuesto_cuentas_view",
    ),
    path(
        "reporteria/anual/centros",
        CtrlGestionView.ctrl_reporte_anual_centros_view,
        name="ctrl_reporte_anual_centros_view",
    ),
    path(
        "reporteria/anual/cuentas",
        CtrlGestionView.ctrl_reporte_anual_cuentas_view,
        name="ctrl_reporte_anual_cuentas_view",
    ),
    path(
        "reporteria/gastos",
        CtrlGestionView.ctrl_reporte_gastos_view,
        name="ctrl_reporte_gastos_view",
    ),
    path(
        "reporteria/ingresos",
        CtrlGestionView.ctrl_reporte_ingresos_view,
        name="ctrl_reporte_ingresos_view",
    ),
    path(
        "reporteria/proyecciones/presupuestos",
        CtrlGestionView.ctrl_reporte_proyecciones_presupuestos_view,
        name="ctrl_reporte_proyecciones_presupuestos_view",
    ),
    path(
        "reporteria/saldos/cuentas",
        CtrlGestionView.ctrl_reporte_saldo_cuentas_view,
        name="ctrl_reporte_saldo_cuentas_view",
    ),
    path("dataAcreedores", CtrlGestionView.dataAcreedores, name="dataAcreedores"),
    path(
        "getNextAcreedorCode",
        CtrlGestionView.getNextAcreedorCode,
        name="getNextAcreedorCode",
    ),
    path("createAcreedor", CtrlGestionView.createAcreedor, name="createAcreedor"),
    path("dataCentros", CtrlGestionView.dataCentros, name="dataCentros"),
    path(
        "dataResponsablesDisponibles",
        CtrlGestionView.dataResponsablesDisponibles,
        name="dataResponsablesDisponibles",
    ),
    path(
        "dataResponsablesCentro",
        CtrlGestionView.dataResponsablesCentro,
        name="dataResponsablesCentro",
    ),
    path(
        "dataCanalesFormato",
        CtrlGestionView.dataCanalesFormato,
        name="dataCanalesFormato",
    ),
    path(
        "addResponsablesCentro",
        CtrlGestionView.addResponsablesCentro,
        name="addResponsablesCentro",
    ),
    path(
        "removeResponsablesCentro",
        CtrlGestionView.removeResponsablesCentro,
        name="removeResponsablesCentro",
    ),
    path(
        "insert_update_centro_vaic",
        CtrlGestionView.insert_update_centro_vaic,
        name="insert_update_centro_vaic",
    ),
    path(
        "validate_autorizacion_tipo",
        CtrlGestionView.validate_autorizacion_tipo,
        name="validate_autorizacion_tipo",
    ),
    path(
        "ctrl_gestion_realizar_cierre_centros",
        CtrlGestionView.ctrl_gestion_realizar_cierre_centros,
        name="ctrl_gestion_realizar_cierre_centros",
    ),
    path(
        "revisar_gasto_vaic",
        CtrlGestionView.revisar_gasto_vaic,
        name="revisar_gasto_vaic",
    ),
    path(
        "guardar_presupuestos_vaic",
        CtrlGestionView.guardar_presupuestos_vaic,
        name="guardar_presupuestos_vaic",
    ),
    path(
        "replicar_presupuestos_centro_vaic",
        CtrlGestionView.replicar_presupuestos_centro_vaic,
        name="replicar_presupuestos_centro_vaic",
    ),
    path(
        "replicar_presupuestos_ingresos_centro",
        CtrlGestionView.replicar_presupuestos_ingresos_centro,
        name="replicar_presupuestos_ingresos_centro",
    ),
    path(
        "anular_proyeccion_vendedor",
        CtrlGestionView.anular_proyeccion_vendedor,
        name="anular_proyeccion_vendedor",
    ),
    path(
        "edit_proyeccion_vendedor",
        CtrlGestionView.edit_proyeccion_vendedor,
        name="edit_proyeccion_vendedor",
    ),
    path(
        "request_updated_data",
        CtrlGestionView.request_updated_data,
        name="request_updated_data",
    ),
    path(
        "update_presupuesto_ingreso",
        CtrlGestionView.update_presupuesto_ingreso,
        name="update_presupuesto_ingreso",
    ),
    path(
        "anular_presupuesto_ingreso",
        CtrlGestionView.anular_presupuesto_ingreso,
        name="anular_presupuesto_ingreso",
    ),
    path(
        "update_presupuesto_proforma_vaic",
        CtrlGestionView.update_presupuesto_proforma_vaic,
        name="update_presupuesto_proforma_vaic",
    ),
    path(
        "save_configuracion_porcentajes_centros",
        CtrlGestionView.save_configuracion_porcentajes_centros,
        name="save_configuracion_porcentajes_centros",
    ),
    path(
        "finalizar_presupuestos_vaic",
        CtrlGestionView.finalizar_presupuestos_vaic,
        name="finalizar_presupuestos_vaic",
    ),
    path(
        "update_gasto_presupuesto",
        CtrlGestionView.update_gasto_presupuesto,
        name="update_gasto_presupuesto",
    ),
    path(
        "autorizar_rechazar_solicitud_gasto",
        CtrlGestionView.autorizar_rechazar_solicitud_gasto,
        name="autorizar_rechazar_solicitud_gasto",
    ),
    path(
        "autorizar_rechazar_solicitud_ingreso",
        CtrlGestionView.autorizar_rechazar_solicitud_ingreso,
        name="autorizar_rechazar_solicitud_ingreso",
    ),
    path(
        "fill_table_cuentas_contables_cat/<str:opc>",
        CtrlGestionView.fill_table_cuentas_contables_cat,
        name="fill_table_cuentas_contables_cat",
    ),
    path(
        "fill_table_desglose_vendedores/<int:id>/<int:mes1>/<int:anio1>/<int:mes2>/<int:anio2>/",
        CtrlGestionView.fill_table_desglose_vendedores,
        name="fill_table_desglose_vendedores",
    ),
    path(
        "fill_table_presupuesto_anual",
        CtrlGestionView.fill_table_presupuesto_anual,
        name="fill_table_presupuesto_anual",
    ),
    path(
        "fill_table_gastos_presupuestados",
        CtrlGestionView.fill_table_gastos_presupuestados,
        name="fill_table_gastos_presupuestados",
    ),
    path(
        "fill_table_ingresos_presupuestados",
        CtrlGestionView.fill_table_ingresos_presupuestados,
        name="fill_table_ingresos_presupuestados",
    ),
    path(
        "fill_table_gastos", CtrlGestionView.fill_table_gastos, name="fill_table_gastos"
    ),
    path(
        "list_porcentajes_centros",
        CtrlGestionView.fill_table_porcentajes_solicitar,
        name="fill_table_porcentajes_solicitar",
    ),
    path(
        "fill_table_meses_presupuestados",
        CtrlGestionView.fill_table_meses_presupuestados,
        name="fill_table_meses_presupuestados",
    ),
    path(
        "fill_table_cuentas_contables",
        CtrlGestionView.fill_table_cuentas_contables,
        name="fill_table_cuentas_contables",
    ),
    path(
        "fill_table_ajustes_cuentas",
        CtrlGestionView.fill_table_ajustes_cuentas,
        name="fill_table_ajustes_cuentas",
    ),
    path(
        "finalizar_presupuestos_vaic",
        CtrlGestionView.finalizar_presupuestos_vaic,
        name="finalizar_presupuestos_vaic",
    ),
    path(
        "validate_presupuestos_creados_vaic",
        CtrlGestionView.validate_presupuestos_creados_vaic,
        name="validate_presupuestos_creados_vaic",
    ),
    path(
        "validate_proyeccion_presupuesto_vaic",
        CtrlGestionView.validate_proyeccion_presupuesto_vaic,
        name="validate_proyeccion_presupuesto_vaic",
    ),
    path(
        "solicitar_autorizacion",
        CtrlGestionView.solicitar_autorizacion,
        name="solicitar_autorizacion",
    ),
    path(
        "validate_proyeccion_presupuesto_vaic",
        CtrlGestionView.validate_proyeccion_presupuesto_vaic,
        name="validate_proyeccion_presupuesto_vaic",
    ),
    path(
        "save_edit_presupuesto_vaic",
        CtrlGestionView.save_edit_presupuesto_vaic,
        name="save_edit_presupuesto_vaic",
    ),
    path(
        "save_edit_proyeccion_vendedores_vaic",
        CtrlGestionView.save_edit_proyeccion_vendedores_vaic,
        name="save_edit_proyeccion_vendedores_vaic",
    ),
    path(
        "validate_proyeccion_presupuesto_vaic",
        CtrlGestionView.validate_proyeccion_presupuesto_vaic,
        name="validate_proyeccion_presupuesto_vaic",
    ),
    path(
        "get_monto_solicitar_indirecto_centro",
        CtrlGestionView.get_monto_solicitar_indirecto_centro,
        name="get_monto_solicitar_indirecto_centro",
    ),
    path(
        "update_presupuesto_ajuste_vaic",
        CtrlGestionView.update_presupuesto_ajuste_vaic,
        name="update_presupuesto_ajuste_vaic",
    ),
    path(
        "fill_select_servicios",
        CtrlGestionView.fill_select_servicios,
        name="fill_select_servicios",
    ),
    path(
        "save_edit_gastos_indirectos",
        CtrlGestionView.save_edit_gastos_indirectos,
        name="save_edit_gastos_indirectos",
    ),
    path(
        "anular_presupuesto",
        CtrlGestionView.anular_presupuesto,
        name="anular_presupuesto",
    ),
    path(
        "gestion_gasto_indirecto",
        CtrlGestionView.gestion_gasto_indirecto,
        name="gestion_gasto_indirecto",
    ),
    path(
        "gestion_presupuesto_final",
        CtrlGestionView.gestion_presupuesto_final,
        name="gestion_presupuesto_final",
    ),
    path(
        "finalizar_centro_vaic",
        CtrlGestionView.finalizar_centro_vaic,
        name="finalizar_centro_vaic",
    ),
    path(
        "fill_table_centro_servicios",
        CtrlGestionView.fill_table_centro_servicios,
        name="fill_table_centro_servicios",
    ),
    path(
        "change_status_servicios_centro",
        CtrlGestionView.change_status_servicios_centro,
        name="change_status_servicios_centro",
    ),
    path(
        "save_edit_servicios_centro",
        CtrlGestionView.save_edit_servicios_centro,
        name="save_edit_servicios_centro",
    ),
    path(
        "editar_ajuste_cuenta",
        CtrlGestionView.editar_ajuste_cuenta,
        name="editar_ajuste_cuenta",
    ),
    path(
        "guardar_ajuste_cuenta",
        CtrlGestionView.guardar_ajuste_cuenta,
        name="guardar_ajuste_cuenta",
    ),
    path(
        "update_rechazar_ajuste_vaic",
        CtrlGestionView.update_rechazar_ajuste_vaic,
        name="update_rechazar_ajuste_vaic",
    ),
    path(
        "solicitar_ajuste_cuenta",
        CtrlGestionView.solicitar_ajuste_cuenta,
        name="solicitar_ajuste_cuenta",
    ),
    path(
        "fill_table_solicitudes_gastos",
        CtrlGestionView.fill_table_solicitudes_gastos,
        name="fill_table_solicitudes_gastos",
    ),
    path(
        "fill_table_gastos_fuera_presupuesto",
        CtrlGestionView.fill_table_gastos_fuera_presupuesto,
        name="fill_table_gastos_fuera_presupuesto",
    ),
    path(
        "fill_table_gastos_bancario",
        CtrlGestionView.fill_table_gastos_bancario,
        name="fill_table_gastos_bancario",
    ),
    path(
        "fill_table_solicitudes_ingresos",
        CtrlGestionView.fill_table_solicitudes_ingresos,
        name="fill_table_solicitudes_ingresos",
    ),
    path(
        "fill_select_cuentas_centro",
        CtrlGestionView.fill_select_cuentas_centro,
        name="fill_select_cuentas_centro",
    ),
    path(
        "fill_select_cuentas_ingresos_centro",
        CtrlGestionView.fill_select_cuentas_ingresos_centro,
        name="fill_select_cuentas_ingresos_centro",
    ),
    path(
        "save_solicitud_gasto_vaic",
        CtrlGestionView.save_solicitud_gasto_vaic,
        name="save_solicitud_gasto_vaic",
    ),
    path(
        "save_solicitud_ingreso_vaic",
        CtrlGestionView.save_solicitud_ingreso_vaic,
        name="save_solicitud_ingreso_vaic",
    ),
    path(
        "aprobar_gasto_no_presupuesto_vaic",
        CtrlGestionView.aprobar_gasto_no_presupuesto_vaic,
        name="aprobar_gasto_no_presupuesto_vaic",
    ),
    path(
        "get_data_presupuesto",
        CtrlGestionView.get_data_presupuesto,
        name="get_data_presupuesto",
    ),
    path(
        "validate_existe_gastos_fuera_presupuesto",
        CtrlGestionView.validate_existe_gastos_fuera_presupuesto,
        name="validate_existe_gastos_fuera_presupuesto",
    ),
    path(
        "finalizar_ingreso_gastos_vaic",
        CtrlGestionView.finalizar_ingreso_gastos_vaic,
        name="finalizar_ingreso_gastos_vaic",
    ),
    path(
        "insert_gasto_bancario_presupuesto",
        CtrlGestionView.insert_gasto_bancario_presupuesto,
        name="insert_gasto_bancario_presupuesto",
    ),
    path(
        "fill_table_desglose_gastos",
        CtrlGestionView.fill_table_desglose_gastos,
        name="fill_table_desglose_gastos",
    ),
    path(
        "retirar_gasto_vaic",
        CtrlGestionView.retirar_gasto_vaic,
        name="retirar_gasto_vaic",
    ),
    path(
        "dataBalancePresupuestoCentros",
        CtrlGestionView.dataBalancePresupuestoCentros,
        name="dataBalancePresupuestoCentros",
    ),
    path(
        "dataBalancePresupuestosCentrosVAIC",
        CtrlGestionView.dataBalancePresupuestosCentrosVAIC,
        name="dataBalancePresupuestosCentrosVAIC",
    ),
    path(
        "dataBalancePresupuestosCuentasVAIC",
        CtrlGestionView.dataBalancePresupuestosCuentasVAIC,
        name="dataBalancePresupuestosCuentasVAIC",
    ),
    path(
        "dataCentrosCuentaPresupuestada",
        CtrlGestionView.dataCentrosCuentaPresupuestada,
        name="dataCentrosCuentaPresupuestada",
    ),
    path(
        "dataComparativaAnualCentros",
        CtrlGestionView.dataComparativaAnualCentros,
        name="dataComparativaAnualCentros",
    ),
    path(
        "dataComparativaAnualCuentasContables",
        CtrlGestionView.dataComparativaAnualCuentasContables,
        name="dataComparativaAnualCuentasContables",
    ),
    path(
        "dataReporteGastosPresupuestos",
        CtrlGestionView.dataReporteGastosPresupuestos,
        name="dataReporteGastosPresupuestos",
    ),
    path(
        "dataReporteGastosIngresados",
        CtrlGestionView.dataReporteGastosIngresados,
        name="dataReporteGastosIngresados",
    ),
    path(
        "dataReporteIngresosPresupuestos",
        CtrlGestionView.dataReporteIngresosPresupuestos,
        name="dataReporteIngresosPresupuestos",
    ),
    path(
        "dataReporteIngresosLogrados",
        CtrlGestionView.dataReporteIngresosLogrados,
        name="dataReporteIngresosLogrados",
    ),
    path("dataReporteEVA", CtrlGestionView.dataReporteEVA, name="dataReporteEVA"),
    path(
        "dataVendedoresCentro",
        CtrlGestionView.dataVendedoresCentro,
        name="dataVendedoresCentro",
    ),
    path(
        "dataGastosPresupuesto",
        CtrlGestionView.dataGastosPresupuesto,
        name="dataGastosPresupuesto",
    ),
    path(
        "conta/listar-cuentas/",
        CtrlGestionView.list_all_cuentas_contables,
        name="list_all_cuentas_contables",
    ),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
