# Generated by Django 2.2 on 2025-02-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MgRuta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_vendedor', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('codigo_vendedor', models.IntegerField(blank=True, null=True)),
                ('id_supervisor', models.IntegerField(blank=True, null=True)),
                ('codigo_supervisor', models.IntegerField(blank=True, null=True)),
                ('nombre_supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('id_canal', models.IntegerField(blank=True, null=True)),
                ('canal', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mg_rutas',
            },
        ),
        migrations.CreateModel(
            name='TelefonoAccesoRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_verificacion', models.IntegerField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_vendedor', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('registrado_por', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'telefonos_accesosrutas',
            },
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificacion', models.IntegerField(blank=True, null=True)),
                ('registrado', models.BooleanField(default=False)),
                ('nombre_empleado', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('imei_1', models.CharField(blank=True, db_column='IMEI 1', max_length=255, null=True)),
                ('id_telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('id_vendedor', models.IntegerField(default=1)),
                ('id_supervisor', models.IntegerField(default=1)),
                ('venta_pma', models.BooleanField(default=False)),
                ('venta_carbajal', models.BooleanField(default=False)),
                ('acceso_total', models.BooleanField(default=True)),
                ('usuario', models.CharField(default=None, max_length=255, null=True)),
                ('perfil_empleado', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'telefonos',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_vendedor', models.IntegerField(blank=True, null=True)),
                ('nombre_vendedor', models.CharField(blank=True, max_length=25, null=True)),
                ('id_sucursal', models.IntegerField(blank=True, null=True)),
                ('id_supervisor', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendedores',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('id_telegram', models.CharField(blank=True, max_length=15, null=True)),
                ('es_jefe', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('id_supervisor', models.IntegerField(default=0)),
                ('porcentaje', models.DecimalField(decimal_places=1, default=0.0, max_digits=12)),
                ('it', models.BooleanField(blank=True, null=True)),
                ('es_supervisor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'supervisor',
                'unique_together': {('id',)},
            },
        ),
    ]
