# Generated by Django 2.2 on 2025-02-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicionMenu', models.CharField(max_length=100)),
                ('tiene_acceso', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('usuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.IntegerField(default=1, help_text='1 ACTIVO| 2 RETIRADO')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('is_built_in', models.BooleanField(default=False)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('pass_requerido', models.IntegerField(default=0)),
                ('ventas', models.BooleanField(default=False)),
                ('comisiones', models.BooleanField(default=False)),
                ('fk_puesto', models.IntegerField(default=0)),
                ('correo', models.CharField(default=' ', max_length=100)),
                ('id_telegram', models.CharField(default=' ', help_text='-880470424 <----- ESTE ID TELEGRAM ES GENERAL PARA EVITAR ERRORES CON EL API DEL BOT AL MOMENTO DE NO ENCONTRAR UN ID TELEGRAM', max_length=30)),
                ('identidad', models.CharField(default=' ', max_length=20)),
                ('telefono', models.CharField(default=' ', max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fk_cargo', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
